name: Trigger PDF Build in ch.minova.doku

on:
  workflow_dispatch:
    inputs:
      projektname:
        description: Projektname im Unterordner `projekte/`
        required: true
        type: string
      titel:
        description: Dokumenttitel (title in metadata.yml)
        required: true
        type: string
      autor:
        description: Autor (author in metadata.yml)
        required: true
        type: string
      firma:
        description: Firma (company in metadata.yml)
        required: true
        type: string
      datum:
        description: Datum (z. B. 14.07.2025)
        required: false
        type: string

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Action in ch.minova.doku triggern
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: minova-afis/ch.minova.doku
          event-type: build-pdf
          client-payload: |
            {
              "projektname": "${{ github.event.inputs.projektname }}",
              "title": "${{ github.event.inputs.titel }}",
              "author": "${{ github.event.inputs.autor }}",
              "company": "${{ github.event.inputs.firma }}",
              "date": "${{ github.event.inputs.datum }}"
            }
