name: Delete Obsolete Packages
on:
  workflow_call:
    inputs:
      min-versions-to-keep:
        description: 'minimum number of versions to keep'
        type: number
        default: 3
      package-name:
        description: 'Name of the package to be deleted'
        type: string
        required: true
      package-type:
        description: 'Type of the package. Can be one of container, maven, npm, nuget, or rubygems'
        type: string
        default: 'maven'
    secrets:
      DELETE_PACKAGE:
        required: true

jobs:
  delete:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: delete '${{inputs.package-name}}' packages
        uses: actions/delete-package-versions@v5
        with:
          #repo: 'aero.minova.maven.root'
          package-name: ${{inputs.package-name}}
          package-type: ${{inputs.package-type}}
          min-versions-to-keep: 3
          token: ${{ secrets.DELETE_PACKAGE }}


