name: Generate OpenAPI Client with kubb.dev

on:
  workflow_call:
    inputs:
      openapi-specification:
        description: 'OpenAPI specification in YAML format used by kubb.dev'
        type: string
        default: 'typescript-angular.config.json'
      base-package-as-path:
        description: "Path where the generated client should be stored"
        type: string
        required: true

jobs:
  generate-client-typescript:
    name: Generate TypeScript Client with Kubb
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8.0.1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Skip commits by 'maven-release-plugin'
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if [[ $commit_message == *"[maven-release-plugin]"* ]]; then
            echo "Commit initiated by 'maven-release-plugin'. Skipping workflow..."
            exit 78
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies (ci fallback)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "⚠️ package-lock.json not found, using npm install"
            npm install --legacy-peer-deps
          fi
  

      - name: Generate API client using Kubb
        run: npx kubb

      - name: Publish NPM package
        if: steps.branch-name.outputs.ref_branch == 'main'
        run: |
          cd ${{ inputs.base-package-as-path }}
          npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MAIN_GITHUB_RELEASE_TOKEN }}
