name: Release Java applications
run-name: Release Java applications ${{ inputs.release-version }}
on:
  workflow_call:
    inputs:
# TODO do-containerize mit release-type zum laufen bringen.
#      do-containerize:
#        description: 'Should CI flow create a container image?'
#        type: boolean
#        default: false
      container-name:
        description: 'Alternative name for the container-image, otherwise \$github.event.repository.name'
        type: string
        default: ${{ github.event.repository.name }}
      registry:
        description: 'Container registry to be used, e.g. ghcr.io, docker.io'
        type: string
        default: 'ghcr.io'
      folder:
        description: 'Folder of the software project to be released in the repo.'
        type: string
        default: './'
      release-type:
        type: choice
        description: Type of release
        options:
        - patch
        - minor
        - major
      java-version:
        description: 'This is the version of Java used for release.'
        type: string
        default: '21'
    outputs:
      container-image:
        description: "Fully qualified name of the prepared container image"
        value: ${{jobs.build.outputs.container-image}}

jobs:
  release:
    name: release, containerize ... repeat
    runs-on: ubuntu-latest
    outputs:
      container-image: ${{steps.container-name-and-githash.outputs.container-image}}

    strategy:
      matrix:
        java-version:
          - ${{inputs.java-version}}

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MAIN_GITHUB_REPO_FULL_ACCESS }}

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          java-package: 'jdk'
          cache: 'maven'

      - name: Maven release '${{ inputs.release-type }}'
        shell: bash
        run: |
          git config --global user.email "service@minova.com"
          git config --global user.name "minova-worker"
          cd $GITHUB_WORKSPACE/${{inputs.folder}}
          mvn --batch-mode --no-transfer-progress \
            -P repo-github \
            release:prepare release:perform \
            -Dusername=$GITHUB_ACCESS_TOKEN \
            -Dpassword=$GITHUB_ACCESS_TOKEN \
            -Darguments="-Dmaven.javadoc.skip=true" \
            -Darguments="-DAWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} -DAWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --settings $GITHUB_WORKSPACE/.github/settings.xml
        env:
          MAIN_GITHUB_RELEASE_USERNAME: ${{ secrets.MAIN_GITHUB_RELEASE_USERNAME }}
          MAIN_GITHUB_RELEASE_TOKEN: ${{ secrets.MAIN_GITHUB_RELEASE_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.MAIN_GITHUB_RELEASE_TOKEN }}

      - name: prepare container image name
        if: inputs.do-containerize == true
        id: container-name-and-githash
        shell: bash
        run: |
          GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)
          echo "github_sha_short=$GITHUB_SHA_SHORT" >> $GITHUB_OUTPUT
          echo "container-image=${{inputs.registry}}/${{github.repository_owner}}/${{ inputs.container-name }}:${{ inputs.release-type }}" >> $GITHUB_OUTPUT

