name: release V12 applications
on:
  workflow_call:
    inputs:
      do-containerize:
        description: 'Should CI flow create a container image?'
        type: boolean
        default: false
      container-name:
        description: 'Alternative name for the container-image, otherwise \$github.event.repository.name'
        type: string
        default: ${{ github.event.repository.name }}
      registry:
        description: 'Container registry to be used, e.g. ghcr.io, docker.io'
        type: string
        default: 'ghcr.io'
      release-version:
        description: 'Version string of this release'
        type: string
        required: true
    outputs:
      container-image:
        description: "Fully qualified name of the prepared container image"
        value: ${{jobs.build.outputs.container-image}}

jobs:
  release:
    name: release, containerize ... repeat
    runs-on: ubuntu-latest
    outputs:
      container-image: ${{steps.container-name-and-githash.outputs.container-image}}

    strategy:
      matrix:
        java-version: ['21']

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MAIN_GITHUB_REPO_FULL_ACCESS }}

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          java-package: 'jdk'
          cache: 'maven'

      - name: Maven release '${{ inputs.release-version }}'
        shell: bash
        run: |
          git config --global user.email "service@minova.com"
          git config --global user.name "minova-worker"
          cd $GITHUB_WORKSPACE/
          mvn --batch-mode --no-transfer-progress \
            -P repo-github \
            release:prepare release:perform \
            -Dusername=$GITHUB_ACCESS_TOKEN \
            -Dpassword=$GITHUB_ACCESS_TOKEN \
            -DreleaseVersion=${{ inputs.release-version }} \
            -Darguments="-Dmaven.javadoc.skip=true" \
            -Darguments="-DAWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} -DAWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --settings .github/settings.xml
        env:
          MAIN_GITHUB_RELEASE_USERNAME: ${{ secrets.MAIN_GITHUB_RELEASE_USERNAME }}
          MAIN_GITHUB_RELEASE_TOKEN: ${{ secrets.MAIN_GITHUB_RELEASE_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.MAIN_GITHUB_RELEASE_TOKEN }}

      - name: prepare container image name
        if: inputs.do-containerize == true
        id: container-name-and-githash
        shell: bash
        run: |
          GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)
          echo "github_sha_short=$GITHUB_SHA_SHORT" >> $GITHUB_OUTPUT
          echo "container-image=${{inputs.registry}}/${{github.repository_owner}}/${{ inputs.container-name }}:${{ inputs.release-version }}" >> $GITHUB_OUTPUT

      - name: build & push container image '${{ steps.container-name-and-githash.outputs.container-image }}'
        if: inputs.do-containerize == true
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ inputs.container-name }}
          addLatest: true
          tags: ${{ inputs.release-version }}, latest
          registry: ${{ inputs.registry }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
