name: Release module
run-name: Release ${{ inputs.release-version }}
on:
  workflow_call:
    inputs:
      release-version:
        description: 'Version string of this release'
        type: string
        required: false
      java-version:
        description: 'This is the version of Java used for release.'
        type: string
        default: '8'

jobs:
  Release:
    uses: minova-afis/aero.minova.os.github.workflows/.github/workflows/release-module.yml@main
    secrets: inherit
    with:
      do-containerize: false
      java-version: ${{ github.event.inputs.java-version }}
      release-version: ${{ github.event.inputs.release-version }}
