name: Release module
run-name: Release ${{ inputs.release-version }}
on:
  workflow_call:
    inputs:
      release-version:
        description: 'Version string of this release'
        type: string
        required: true
      java-version:
        description: 'This is the version of Java used for release.'
        type: string
        default: '11'
        required: false

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MAIN_GITHUB_REPO_FULL_ACCESS }}

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}
          java-package: 'jdk'
          cache: 'maven'

      - name: Maven release '${{ inputs.release-version }}'
        shell: bash
        run: |
          git config --global user.email "service@minova.com"
          git config --global user.name "minova-worker"
          mvn --batch-mode --no-transfer-progress \
            -P repo-github \
            release:prepare release:perform \
            -Dusername=$GITHUB_ACCESS_TOKEN \
            -Dpassword=$GITHUB_ACCESS_TOKEN \
            -DreleaseVersion=${{ inputs.release-version }} \
            -Darguments="-Dmaven.javadoc.skip=true" \
            --settings $GITHUB_WORKSPACE/.github/settings.xml
        env:
          MAIN_GITHUB_RELEASE_USERNAME: ${{ secrets.MAIN_GITHUB_RELEASE_USERNAME }}
          MAIN_GITHUB_RELEASE_TOKEN: ${{ secrets.MAIN_GITHUB_RELEASE_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.MAIN_GITHUB_RELEASE_TOKEN }}
